### ISSUE TITLE
这里的字好像被改坏掉了，看看能不能找回一下以前的版本

### ISSUE THREAD

**Issue by DreUncle** [darwinia-network/crab-home#25]
![image](https://user-images.githubusercontent.com/34929683/147729585-2bbd86b8-2870-4c68-a3f6-376ffdddaeb5.png)

**Comment by DreUncle** [comment]
![image](https://user-images.githubusercontent.com/34929683/147729695-af7b4297-fff2-4541-8fc2-58bd77ff8be8.png)
以前是这样的

**Comment by sxlwar** [comment]
恢复不了了，天坑

**Comment by 1022ranji** [comment]
cc @WoeOm 有以前的版本可以替换吗

**Comment by JayJay1024** [comment]
https://github.com/darwinia-network/crab-home/pull/49
这个pr修复了 @1022ranji

**Comment by 1022ranji** [comment]
done
