### ISSUE TITLE
the contribution history links the old polkadot.subscan.io

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/crab-home#33]
### Prerequisites

- [X] Are you running the latest version?

### Importance

General

### Priority

High

### Description

In My Contribution history, the history tx links the polkadot.subscan.io should be kusama.subscan.io

### How to reproduce this issue

1. contribute
2. query contribution history

### Actual behavior

link to polkadot.subscan.io/tx/0x......

### Expected behavior

link to kusama.subscan.io/tx/0x.....

**Comment by 1022ranji** [comment]
done
