### ISSUE TITLE
Crab PLO 页面数值错误，有推荐历史，但是在my contribution的dashboard中没有显示相应的CRAB和CKTON奖励

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/crab-home#39]
![image](https://user-images.githubusercontent.com/80877629/149314327-c0dbf1c0-340d-4baa-8c99-ec55d7e146d4.png)

**Comment by JayJay1024** [comment]
这个账号地址是什么呢 @1022ranji

**Comment by 1022ranji** [comment]
Cvmr4MrksfUZxKqPJbkoq37dkJRViYtHRfHJpvXSJrj9Thp
