### ISSUE TITLE
Need more clear favicon on the Crab Website.

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/crab-home#66]
Docs' favicon looks clear, but the favicon on the Crab Website is a little bit vague.
![image](https://user-images.githubusercontent.com/80877629/179697426-bc553181-8588-4fcf-8e45-89ae5704bcc5.png)

**Comment by isunaslabs** [comment]
I see. It is now a png file, I'll change it to svg like in the Crab Docs
