### ISSUE TITLE
Add The "Brand" Link.

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/crab-home#69]
Link To: https://itering.notion.site/About-Crab-Network-db5d28d1479540118c1f772ebac5783c
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/80877629/192419487-08caffa4-c0b4-4615-8a05-931632ffd9bd.png">

**Comment by isunaslabs** [comment]
@1022ranji this issue was fixed already. I guess we should close it.

**Comment by 1022ranji** [comment]
done
